#   SPDX-License-Identifier: BSD-3-Clause
#   Copyright(c) 2018 Marvell International Ltd.

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_LIBRTE_MVEP_COMMON) += mvep

include $(RTE_SDK)/mk/rte.subdir.mk
